
import { Theme } from './types';

export const PREDEFINED_THEMES: Theme[] = [
  { id: '1', label: 'My Family', icon: '👨‍👩‍👧‍👦', description: 'Introduce your family members.' },
  { id: '2', label: 'My School', icon: '🏫', description: 'Describe your school and classroom.' },
  { id: '3', label: 'The Park', icon: '🌳', description: 'Children playing in a beautiful park.' },
  { id: '4', label: 'My Pet', icon: '🐶', description: 'Talk about your lovely dog or cat.' },
  { id: '5', label: 'The Beach', icon: '🏖️', description: 'A sunny day at the seashore.' },
  { id: '6', label: 'Zoo Animals', icon: '🦁', description: 'Wild animals at the city zoo.' },
  { id: '7', label: 'Breakfast', icon: '🍳', description: 'What we eat in the morning.' },
  { id: '8', label: 'My Bedroom', icon: '🛏️', description: 'Describe your favorite room.' },
  { id: '9', label: 'Birthday Party', icon: '🎂', description: 'Balloons, cake, and friends.' },
  { id: '10', label: 'Rainy Day', icon: '🌧️', description: 'Playing with umbrellas in the rain.' },
  { id: '11', label: 'Fruit Market', icon: '🍎', description: 'Yummy fruits in a colorful market.' },
  { id: '12', label: 'Space Adventure', icon: '🚀', description: 'Astronauts and planets.' },
  { id: '13', label: 'Under the Sea', icon: '🐟', description: 'Fish, corals, and treasure.' },
  { id: '14', label: 'Farm Life', icon: '🐄', description: 'Cows, chickens, and a red barn.' },
  { id: '15', label: 'Sports Day', icon: '⚽', description: 'Running and playing games.' },
  { id: '16', label: 'Cooking', icon: '👩‍🍳', description: 'Baking cookies in the kitchen.' },
  { id: '17', label: 'Library', icon: '📚', description: 'Quiet time with magic books.' },
  { id: '18', label: 'Playground', icon: '🛝', description: 'Slides and swings.' },
  { id: '19', label: 'Four Seasons', icon: '🍂', description: 'Spring, Summer, Autumn, Winter.' },
  { id: '20', label: 'Best Friend', icon: '👫', description: 'Playing together with a friend.' },
  { id: '21', label: 'Transport', icon: '🚂', description: 'Cars, trains, and planes.' },
  { id: '22', label: 'Jungle Safari', icon: '🐘', description: 'Deep jungle exploration.' },
  { id: '23', label: 'The Garden', icon: '🌻', description: 'Flowers and butterflies.' },
  { id: '24', label: 'Shopping Mall', icon: '🛍️', description: 'Buying toys and clothes.' },
  { id: '25', label: 'The Cinema', icon: '🍿', description: 'Watching a fun movie.' },
  { id: '26', label: 'Camping', icon: '⛺', description: 'Tents and a campfire at night.' },
  { id: '27', label: 'Ice Cream', icon: '🍦', description: 'Choosing flavors at a shop.' },
  { id: '28', label: 'Music Class', icon: '🎸', description: 'Playing instruments.' },
  { id: '29', label: 'Art Studio', icon: '🎨', description: 'Painting and drawing.' },
  { id: '30', label: 'Robot World', icon: '🤖', description: 'High-tech friendly robots.' },
];
